export const POSTS_REQUEST_LOADING = "POSTS_REQUEST_LOADING";
export const POSTS_SUCCESSFULL = "POSTS_REQUEST_SUCCESSFULL";
export const POSTS_REQUEST_FAILED = "POSTS_REQUEST_FAILED";

export const POST_REQUEST_LOADING = "POST_REQUEST_LOADING";
export const POST_SUCCESSFULL = "POST_REQUEST_SUCCESSFULL";
export const POST_REQUEST_FAILED = "POST_REQUEST_FAILED";

export const POST_ADDED = "POST_ADDED";

export const REACTION_ADDED = "REACTION_ADDED";
export const REACTION_REMOVED = "REACTION_REMOVED";

export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_REMOVED = "COMMENT_REMOVED";
